services:
  api-server:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      - PYTHONPATH=/app
    env_file: .env
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - app-db-marker:/app/data
    restart: always

volumes:
  app-db-marker:
