--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

-- Started on 2026-09-10 22:41:16

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 227 (class 1259 OID 17292)
-- Name: attachments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.attachments (
    id integer NOT NULL,
    meeting_id integer NOT NULL,
    is_file boolean NOT NULL,
    name character varying NOT NULL
);


ALTER TABLE public.attachments OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 17259)
-- Name: departments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.departments (
    id integer NOT NULL,
    name character varying NOT NULL,
    parent_id integer,
    manager_id integer NOT NULL
);


ALTER TABLE public.departments OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 17244)
-- Name: fields; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fields (
    id integer NOT NULL,
    name character varying NOT NULL
);


ALTER TABLE public.fields OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 17243)
-- Name: fields_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.fields ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fields_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 17271)
-- Name: meetings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.meetings (
    id integer NOT NULL,
    inspector_id integer NOT NULL,
    user_id integer NOT NULL,
    date timestamp with time zone NOT NULL,
    totals character varying
);


ALTER TABLE public.meetings OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 17270)
-- Name: meetings_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.meetings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.meetings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 17277)
-- Name: skill_marks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.skill_marks (
    id integer NOT NULL,
    mark integer NOT NULL,
    meeting_id integer NOT NULL,
    problems_comm character varying,
    skill_id integer NOT NULL,
    is_defended boolean NOT NULL
);


ALTER TABLE public.skill_marks OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 17276)
-- Name: skill_marks_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.skill_marks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.skill_marks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 17236)
-- Name: skills; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.skills (
    id integer NOT NULL,
    name character varying NOT NULL,
    field_id integer NOT NULL
);


ALTER TABLE public.skills OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 17252)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id integer NOT NULL,
    login character varying NOT NULL,
    email character varying,
    hash_password character(100) NOT NULL,
    department_id integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    is_hired boolean NOT NULL,
    field_id integer NOT NULL,
    name character varying NOT NULL,
    otchestvo character varying,
    surname character varying NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 17251)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4942 (class 0 OID 17292)
-- Dependencies: 227
-- Data for Name: attachments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.attachments (id, meeting_id, is_file, name) FROM stdin;
\.


--
-- TOC entry 4937 (class 0 OID 17259)
-- Dependencies: 222
-- Data for Name: departments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.departments (id, name, parent_id, manager_id) FROM stdin;
\.


--
-- TOC entry 4934 (class 0 OID 17244)
-- Dependencies: 219
-- Data for Name: fields; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.fields (id, name) FROM stdin;
\.


--
-- TOC entry 4939 (class 0 OID 17271)
-- Dependencies: 224
-- Data for Name: meetings; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.meetings (id, inspector_id, user_id, date, totals) FROM stdin;
\.


--
-- TOC entry 4941 (class 0 OID 17277)
-- Dependencies: 226
-- Data for Name: skill_marks; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.skill_marks (id, mark, meeting_id, problems_comm, skill_id, is_defended) FROM stdin;
\.


--
-- TOC entry 4932 (class 0 OID 17236)
-- Dependencies: 217
-- Data for Name: skills; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.skills (id, name, field_id) FROM stdin;
\.


--
-- TOC entry 4936 (class 0 OID 17252)
-- Dependencies: 221
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, login, email, hash_password, department_id, created_at, is_hired, field_id, name, otchestvo, surname) FROM stdin;
\.


--
-- TOC entry 4948 (class 0 OID 0)
-- Dependencies: 218
-- Name: fields_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.fields_id_seq', 1, false);


--
-- TOC entry 4949 (class 0 OID 0)
-- Dependencies: 223
-- Name: meetings_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.meetings_id_seq', 1, false);


--
-- TOC entry 4950 (class 0 OID 0)
-- Dependencies: 225
-- Name: skill_marks_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.skill_marks_id_seq', 1, false);


--
-- TOC entry 4951 (class 0 OID 0)
-- Dependencies: 220
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 1, false);


--
-- TOC entry 4786 (class 2606 OID 17298)
-- Name: attachments attachments_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.attachments
    ADD CONSTRAINT attachments_pk PRIMARY KEY (id);


--
-- TOC entry 4776 (class 2606 OID 17265)
-- Name: departments departments_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_pk PRIMARY KEY (id);


--
-- TOC entry 4778 (class 2606 OID 17267)
-- Name: departments departments_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_unique UNIQUE (name);


--
-- TOC entry 4780 (class 2606 OID 17269)
-- Name: departments departments_unique_1; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_unique_1 UNIQUE (manager_id);


--
-- TOC entry 4772 (class 2606 OID 17250)
-- Name: fields fields_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fields
    ADD CONSTRAINT fields_pk PRIMARY KEY (id);


--
-- TOC entry 4782 (class 2606 OID 17275)
-- Name: meetings meetings_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meetings
    ADD CONSTRAINT meetings_pk PRIMARY KEY (id);


--
-- TOC entry 4784 (class 2606 OID 17283)
-- Name: skill_marks skill_marks_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.skill_marks
    ADD CONSTRAINT skill_marks_pk PRIMARY KEY (id);


--
-- TOC entry 4770 (class 2606 OID 17242)
-- Name: skills skills_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.skills
    ADD CONSTRAINT skills_pk PRIMARY KEY (id);


--
-- TOC entry 4774 (class 2606 OID 17258)
-- Name: users users_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pk PRIMARY KEY (id);


-- Completed on 2026-09-10 22:41:16

--
-- PostgreSQL database dump complete
--

